---
name: Dependency drift tracker
description: >
  Track your dependency drift across multiple repositories using libyear.
author: François de Metz
branding:
  color: blue
  icon: code
inputs:
  commit-message:
    description: 'The message of the update commit'
    required: false
    default: 'Update data'
  user-name:
    description: 'The user name of the commit'
    required: false
    default: 'Dependency drift tracker'
  user-email:
    description: 'The user email of the commit'
    required: false
    default: 'dependency-drift-tracker@users.noreply.github.com'
runs:
  using: node20
  main: dist/index.mjs
